// <auto-generated />
using System;
using MeetingsAPI.Enitities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeetingsAPI.Migrations
{
    [DbContext(typeof(MeetupContext))]
    [Migration("20200317233804_AddSpecialGuestsRelation")]
    partial class AddSpecialGuestsRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeetingsAPI.Enitities.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Description");

                    b.Property<string>("Language");

                    b.Property<int>("MeetupId");

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.HasIndex("MeetupId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("MeetingsAPI.Enitities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<int>("MeetupId");

                    b.Property<string>("PostCode");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.HasIndex("MeetupId")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MeetingsAPI.Enitities.Meetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("Name");

                    b.Property<string>("Organizer");

                    b.HasKey("Id");

                    b.ToTable("Meetups");
                });

            modelBuilder.Entity("MeetingsAPI.Enitities.SpecialGuest", b =>
                {
                    b.Property<int>("SpecialGuestId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Citzenship");

                    b.Property<string>("Company");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("SpecialGuestId");

                    b.ToTable("SpecialGuests");
                });

            modelBuilder.Entity("MeetingsAPI.Enitities.SpecialGuestJoint", b =>
                {
                    b.Property<int>("MeetupId");

                    b.Property<int>("FirstSpecialGuestId");

                    b.Property<int>("SecondSpecialGuestId");

                    b.Property<int>("Id");

                    b.HasKey("MeetupId", "FirstSpecialGuestId", "SecondSpecialGuestId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("FirstSpecialGuestId");

                    b.HasIndex("SecondSpecialGuestId");

                    b.ToTable("SpecialGuestJoint");
                });

            modelBuilder.Entity("MeetingsAPI.Enitities.Lecture", b =>
                {
                    b.HasOne("MeetingsAPI.Enitities.Meetup", "Meetup")
                        .WithMany("Lectures")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MeetingsAPI.Enitities.Location", b =>
                {
                    b.HasOne("MeetingsAPI.Enitities.Meetup", "Meetup")
                        .WithOne("Location")
                        .HasForeignKey("MeetingsAPI.Enitities.Location", "MeetupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MeetingsAPI.Enitities.SpecialGuestJoint", b =>
                {
                    b.HasOne("MeetingsAPI.Enitities.SpecialGuest", "FirstSpecialGuests")
                        .WithMany("FirstSpecialGuestJoints")
                        .HasForeignKey("FirstSpecialGuestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MeetingsAPI.Enitities.Meetup", "Meetup")
                        .WithMany("SpecialGuestJoints")
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MeetingsAPI.Enitities.SpecialGuest", "SecondSpecialGuests")
                        .WithMany("SecondSpecialGuestJoints")
                        .HasForeignKey("SecondSpecialGuestId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
